### ISSUE TITLE
谁跟我说写js肯定要分号的？

### ISSUE THREAD

**Issue by ZYSzys** [yewenjunfighting/questionnairProject#1]
[webpack.config.js](https://github.com/yewenjunfighting/questionnairProject/blob/fc9bd413a06c23ac2657dc0003aa476c40ae741c/webpack.config.js#L1)
黑人问号脸？？？？

**Comment by yewenjunfighting** [comment]
我没说一定要用分号，在有些是时候是可以不用的

**Comment by ZYSzys** [comment]
我：“看了一波网上的争论，写js要不要写分号。最后我决定还是写分号吧。”
某人：“肯定要分号的呀！…………”

现在又没说了？

**Comment by yewenjunfighting** [comment]
大部分情况下，不加分号就报错，你加不加？
但肯定有不需要加分号的情况呀

**Comment by yewenjunfighting** [comment]
有时候你不用手动加分号，是因为js会自动帮你补齐的，但它补齐之后样子可能不是你期许的，甚至会引起语法错误,反正加不加取决于你，随你了

**Comment by ZYSzys** [comment]
现在不是跟你讨论要不要写分号的问题，而是说你当时的用词—“肯定要写”。而现在呢？你还这么认为吗？

**Comment by yewenjunfighting** [comment]
不一定要写

**Comment by ZYSzys** [comment]
OK，问题解决。😏
